// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type RegisterResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RegisterResponse) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_UserId = b.UserId
	}
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,2,opt,name=user_id,json=userId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginResponse) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginResponse) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *LoginResponse) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token  *string
	UserId *string
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_UserId = b.UserId
	}
	return m0
}

type Secret struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data         []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Hash         *string                `protobuf:"bytes,3,opt,name=hash"`
	xxx_hidden_LastModified *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_modified,json=lastModified"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Secret) GetHash() string {
	if x != nil {
		if x.xxx_hidden_Hash != nil {
			return *x.xxx_hidden_Hash
		}
		return ""
	}
	return ""
}

func (x *Secret) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastModified
	}
	return nil
}

func (x *Secret) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Secret) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Secret) SetHash(v string) {
	x.xxx_hidden_Hash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Secret) SetLastModified(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastModified = v
}

func (x *Secret) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Secret) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Secret) HasHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Secret) HasLastModified() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastModified != nil
}

func (x *Secret) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Secret) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *Secret) ClearHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Hash = nil
}

func (x *Secret) ClearLastModified() {
	x.xxx_hidden_LastModified = nil
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *string
	Data         []byte
	Hash         *string
	LastModified *timestamppb.Timestamp
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Data = b.Data
	}
	if b.Hash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Hash = b.Hash
	}
	x.xxx_hidden_LastModified = b.LastModified
	return m0
}

type SetSecretRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *SetSecretRequest) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *SetSecretRequest) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *SetSecretRequest) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type SetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 SetSecretRequest_builder) Build() *SetSecretRequest {
	m0 := &SetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type SetSecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *SetSecretResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetSecretResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetSecretResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type SetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 SetSecretResponse_builder) Build() *SetSecretResponse {
	m0 := &SetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type GetSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId    *string                `protobuf:"bytes,1,opt,name=secret_id,json=secretId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		if x.xxx_hidden_SecretId != nil {
			return *x.xxx_hidden_SecretId
		}
		return ""
	}
	return ""
}

func (x *GetSecretRequest) SetSecretId(v string) {
	x.xxx_hidden_SecretId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSecretRequest) HasSecretId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretRequest) ClearSecretId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SecretId = nil
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId *string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SecretId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SecretId = b.SecretId
	}
	return m0
}

type GetSecretResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *GetSecretResponse) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *GetSecretResponse) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *GetSecretResponse) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type GetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 GetSecretResponse_builder) Build() *GetSecretResponse {
	m0 := &GetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type DeleteSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId    *string                `protobuf:"bytes,1,opt,name=secret_id,json=secretId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		if x.xxx_hidden_SecretId != nil {
			return *x.xxx_hidden_SecretId
		}
		return ""
	}
	return ""
}

func (x *DeleteSecretRequest) SetSecretId(v string) {
	x.xxx_hidden_SecretId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteSecretRequest) HasSecretId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteSecretRequest) ClearSecretId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SecretId = nil
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId *string
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SecretId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SecretId = b.SecretId
	}
	return m0
}

type DeleteSecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *DeleteSecretResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteSecretResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteSecretResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type DeleteSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 DeleteSecretResponse_builder) Build() *DeleteSecretResponse {
	m0 := &DeleteSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListSecretsRequest_builder) Build() *ListSecretsRequest {
	m0 := &ListSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListSecretsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *ListSecretsResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

type ListSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
}

func (b0 ListSecretsResponse_builder) Build() *ListSecretsResponse {
	m0 := &ListSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

var File_internal_proto_api_proto protoreflect.FileDescriptor

const file_internal_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/api.proto\x12\bgokeeper\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x81\x01\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12?\n" +
	"\rlast_modified\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\"<\n" +
	"\x10SetSecretRequest\x12(\n" +
	"\x06secret\x18\x01 \x01(\v2\x10.gokeeper.SecretR\x06secret\"-\n" +
	"\x11SetSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10GetSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"=\n" +
	"\x11GetSecretResponse\x12(\n" +
	"\x06secret\x18\x01 \x01(\v2\x10.gokeeper.SecretR\x06secret\"2\n" +
	"\x13DeleteSecretRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"0\n" +
	"\x14DeleteSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12ListSecretsRequest\"A\n" +
	"\x13ListSecretsResponse\x12*\n" +
	"\asecrets\x18\x01 \x03(\v2\x10.gokeeper.SecretR\asecrets2\x8a\x01\n" +
	"\vAuthService\x12A\n" +
	"\bRegister\x12\x19.gokeeper.RegisterRequest\x1a\x1a.gokeeper.RegisterResponse\x128\n" +
	"\x05Login\x12\x16.gokeeper.LoginRequest\x1a\x17.gokeeper.LoginResponse2\xb6\x02\n" +
	"\rSecretService\x12D\n" +
	"\tSetSecret\x12\x1a.gokeeper.SetSecretRequest\x1a\x1b.gokeeper.SetSecretResponse\x12D\n" +
	"\tGetSecret\x12\x1a.gokeeper.GetSecretRequest\x1a\x1b.gokeeper.GetSecretResponse\x12M\n" +
	"\fDeleteSecret\x12\x1d.gokeeper.DeleteSecretRequest\x1a\x1e.gokeeper.DeleteSecretResponse\x12J\n" +
	"\vListSecrets\x12\x1c.gokeeper.ListSecretsRequest\x1a\x1d.gokeeper.ListSecretsResponseB\x12Z\x10./internal/protob\beditionsp\xe8\a"

var file_internal_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_api_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: gokeeper.RegisterRequest
	(*RegisterResponse)(nil),      // 1: gokeeper.RegisterResponse
	(*LoginRequest)(nil),          // 2: gokeeper.LoginRequest
	(*LoginResponse)(nil),         // 3: gokeeper.LoginResponse
	(*Secret)(nil),                // 4: gokeeper.Secret
	(*SetSecretRequest)(nil),      // 5: gokeeper.SetSecretRequest
	(*SetSecretResponse)(nil),     // 6: gokeeper.SetSecretResponse
	(*GetSecretRequest)(nil),      // 7: gokeeper.GetSecretRequest
	(*GetSecretResponse)(nil),     // 8: gokeeper.GetSecretResponse
	(*DeleteSecretRequest)(nil),   // 9: gokeeper.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 10: gokeeper.DeleteSecretResponse
	(*ListSecretsRequest)(nil),    // 11: gokeeper.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 12: gokeeper.ListSecretsResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_internal_proto_api_proto_depIdxs = []int32{
	13, // 0: gokeeper.Secret.last_modified:type_name -> google.protobuf.Timestamp
	4,  // 1: gokeeper.SetSecretRequest.secret:type_name -> gokeeper.Secret
	4,  // 2: gokeeper.GetSecretResponse.secret:type_name -> gokeeper.Secret
	4,  // 3: gokeeper.ListSecretsResponse.secrets:type_name -> gokeeper.Secret
	0,  // 4: gokeeper.AuthService.Register:input_type -> gokeeper.RegisterRequest
	2,  // 5: gokeeper.AuthService.Login:input_type -> gokeeper.LoginRequest
	5,  // 6: gokeeper.SecretService.SetSecret:input_type -> gokeeper.SetSecretRequest
	7,  // 7: gokeeper.SecretService.GetSecret:input_type -> gokeeper.GetSecretRequest
	9,  // 8: gokeeper.SecretService.DeleteSecret:input_type -> gokeeper.DeleteSecretRequest
	11, // 9: gokeeper.SecretService.ListSecrets:input_type -> gokeeper.ListSecretsRequest
	1,  // 10: gokeeper.AuthService.Register:output_type -> gokeeper.RegisterResponse
	3,  // 11: gokeeper.AuthService.Login:output_type -> gokeeper.LoginResponse
	6,  // 12: gokeeper.SecretService.SetSecret:output_type -> gokeeper.SetSecretResponse
	8,  // 13: gokeeper.SecretService.GetSecret:output_type -> gokeeper.GetSecretResponse
	10, // 14: gokeeper.SecretService.DeleteSecret:output_type -> gokeeper.DeleteSecretResponse
	12, // 15: gokeeper.SecretService.ListSecrets:output_type -> gokeeper.ListSecretsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_api_proto_init() }
func file_internal_proto_api_proto_init() {
	if File_internal_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_proto_api_proto_depIdxs,
		MessageInfos:      file_internal_proto_api_proto_msgTypes,
	}.Build()
	File_internal_proto_api_proto = out.File
	file_internal_proto_api_proto_goTypes = nil
	file_internal_proto_api_proto_depIdxs = nil
}
