// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	stypes "github.com/etoneja/go-keeper/internal/server/stypes"
	gomock "github.com/golang/mock/gomock"
	v5 "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockQuerier) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockQuerierMockRecorder) Exec(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQuerier)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockQuerier) Query(ctx context.Context, sql string, args ...any) (v5.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(v5.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQuerierMockRecorder) Query(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQuerier)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockQuerier) QueryRow(ctx context.Context, sql string, args ...any) v5.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(v5.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockQuerierMockRecorder) QueryRow(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockQuerier)(nil).QueryRow), varargs...)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTxManager) WithTx(ctx context.Context, fn func(Querier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxManagerMockRecorder) WithTx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxManager)(nil).WithTx), ctx, fn)
}

// MockUserRepositorier is a mock of UserRepositorier interface.
type MockUserRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositorierMockRecorder
}

// MockUserRepositorierMockRecorder is the mock recorder for MockUserRepositorier.
type MockUserRepositorierMockRecorder struct {
	mock *MockUserRepositorier
}

// NewMockUserRepositorier creates a new mock instance.
func NewMockUserRepositorier(ctrl *gomock.Controller) *MockUserRepositorier {
	mock := &MockUserRepositorier{ctrl: ctrl}
	mock.recorder = &MockUserRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositorier) EXPECT() *MockUserRepositorierMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepositorier) CreateUser(ctx context.Context, q Querier, login, passwordHash string) (*stypes.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, q, login, passwordHash)
	ret0, _ := ret[0].(*stypes.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositorierMockRecorder) CreateUser(ctx, q, login, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositorier)(nil).CreateUser), ctx, q, login, passwordHash)
}

// GetUserByID mocks base method.
func (m *MockUserRepositorier) GetUserByID(ctx context.Context, q Querier, userID string) (*stypes.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, q, userID)
	ret0, _ := ret[0].(*stypes.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositorierMockRecorder) GetUserByID(ctx, q, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepositorier)(nil).GetUserByID), ctx, q, userID)
}

// GetUserByLogin mocks base method.
func (m *MockUserRepositorier) GetUserByLogin(ctx context.Context, q Querier, login string) (*stypes.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, q, login)
	ret0, _ := ret[0].(*stypes.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserRepositorierMockRecorder) GetUserByLogin(ctx, q, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserRepositorier)(nil).GetUserByLogin), ctx, q, login)
}

// MockSecretRepositorier is a mock of SecretRepositorier interface.
type MockSecretRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositorierMockRecorder
}

// MockSecretRepositorierMockRecorder is the mock recorder for MockSecretRepositorier.
type MockSecretRepositorierMockRecorder struct {
	mock *MockSecretRepositorier
}

// NewMockSecretRepositorier creates a new mock instance.
func NewMockSecretRepositorier(ctrl *gomock.Controller) *MockSecretRepositorier {
	mock := &MockSecretRepositorier{ctrl: ctrl}
	mock.recorder = &MockSecretRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepositorier) EXPECT() *MockSecretRepositorierMockRecorder {
	return m.recorder
}

// DeleteSecret mocks base method.
func (m *MockSecretRepositorier) DeleteSecret(ctx context.Context, q Querier, userID, secretID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, q, userID, secretID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretRepositorierMockRecorder) DeleteSecret(ctx, q, userID, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretRepositorier)(nil).DeleteSecret), ctx, q, userID, secretID)
}

// GetSecret mocks base method.
func (m *MockSecretRepositorier) GetSecret(ctx context.Context, q Querier, userID, secretID string) (*stypes.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, q, userID, secretID)
	ret0, _ := ret[0].(*stypes.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockSecretRepositorierMockRecorder) GetSecret(ctx, q, userID, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockSecretRepositorier)(nil).GetSecret), ctx, q, userID, secretID)
}

// ListSecrets mocks base method.
func (m *MockSecretRepositorier) ListSecrets(ctx context.Context, q Querier, userID string) ([]*stypes.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx, q, userID)
	ret0, _ := ret[0].([]*stypes.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockSecretRepositorierMockRecorder) ListSecrets(ctx, q, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockSecretRepositorier)(nil).ListSecrets), ctx, q, userID)
}

// SetSecret mocks base method.
func (m *MockSecretRepositorier) SetSecret(ctx context.Context, q Querier, secret *stypes.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSecret", ctx, q, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSecret indicates an expected call of SetSecret.
func (mr *MockSecretRepositorierMockRecorder) SetSecret(ctx, q, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSecret", reflect.TypeOf((*MockSecretRepositorier)(nil).SetSecret), ctx, q, secret)
}
