// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctl/crypto/interfaces.go

// Package crypto is a generated GoMock package.
package crypto

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCryptor is a mock of Cryptor interface.
type MockCryptor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptorMockRecorder
}

// MockCryptorMockRecorder is the mock recorder for MockCryptor.
type MockCryptorMockRecorder struct {
	mock *MockCryptor
}

// NewMockCryptor creates a new mock instance.
func NewMockCryptor(ctrl *gomock.Controller) *MockCryptor {
	mock := &MockCryptor{ctrl: ctrl}
	mock.recorder = &MockCryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptor) EXPECT() *MockCryptorMockRecorder {
	return m.recorder
}

// CalculateDataHash mocks base method.
func (m *MockCryptor) CalculateDataHash(data []byte) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDataHash", data)
	ret0, _ := ret[0].(string)
	return ret0
}

// CalculateDataHash indicates an expected call of CalculateDataHash.
func (mr *MockCryptorMockRecorder) CalculateDataHash(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDataHash", reflect.TypeOf((*MockCryptor)(nil).CalculateDataHash), data)
}

// DecryptSecretData mocks base method.
func (m *MockCryptor) DecryptSecretData(encryptedData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptSecretData", encryptedData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptSecretData indicates an expected call of DecryptSecretData.
func (mr *MockCryptorMockRecorder) DecryptSecretData(encryptedData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptSecretData", reflect.TypeOf((*MockCryptor)(nil).DecryptSecretData), encryptedData)
}

// DecryptStorageData mocks base method.
func (m *MockCryptor) DecryptStorageData(encryptedData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptStorageData", encryptedData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptStorageData indicates an expected call of DecryptStorageData.
func (mr *MockCryptorMockRecorder) DecryptStorageData(encryptedData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptStorageData", reflect.TypeOf((*MockCryptor)(nil).DecryptStorageData), encryptedData)
}

// EncryptSecretData mocks base method.
func (m *MockCryptor) EncryptSecretData(plainData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptSecretData", plainData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptSecretData indicates an expected call of EncryptSecretData.
func (mr *MockCryptorMockRecorder) EncryptSecretData(plainData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptSecretData", reflect.TypeOf((*MockCryptor)(nil).EncryptSecretData), plainData)
}

// EncryptStorageData mocks base method.
func (m *MockCryptor) EncryptStorageData(plainData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStorageData", plainData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStorageData indicates an expected call of EncryptStorageData.
func (mr *MockCryptorMockRecorder) EncryptStorageData(plainData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStorageData", reflect.TypeOf((*MockCryptor)(nil).EncryptStorageData), plainData)
}

// GenerateServerPassword mocks base method.
func (m *MockCryptor) GenerateServerPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateServerPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateServerPassword indicates an expected call of GenerateServerPassword.
func (mr *MockCryptorMockRecorder) GenerateServerPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateServerPassword", reflect.TypeOf((*MockCryptor)(nil).GenerateServerPassword))
}
